# Konfigurasi SonarQube untuk project api-wh-stockout
sonar.projectKey=api-wh-stockout
sonar.projectName=API Warehouse Stockout
sonar.projectVersion=1.0.0

# Path ke source code
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,*.log,dist/**,build/**,yarn.lock,package-lock.json, run-sonar.js, setup.js

# Path ke test files
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.test.exclusions=node_modules/**

# JavaScript/Node.js specific settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=js

# Di sonar-project.properties tambahkan:
sonar.host.url=${SONARQUBE_URL}
sonar.token=${SONARQUBE_TOKEN}

# Token untuk authentication (akan diisi nanti)
# sonar.login=your-token-here
